In [1]:
import numpy as np

In [2]:
a = np.array([12, 34, 54])
print(a)

[12 34 54]


In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [6]:
b = np.array([[12, 34, 54],
             [23, 4,56],
             [2, 34,6],
             [2, 34,6],
             [2, 34,6],
             ])
print(b)

[[12 34 54]
 [23  4 56]
 [ 2 34  6]
 [ 2 34  6]
 [ 2 34  6]]


In [5]:
print(type(b))

<class 'numpy.ndarray'>


In [7]:
b.shape = (3,5)
print(b)

[[12 34 54 23  4]
 [56  2 34  6  2]
 [34  6  2 34  6]]


In [16]:
b
b.ndim

2

In [9]:
pip install numpy


[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
pip install pandas

In [11]:
pip install --upgrade pip

  Using cached pip-25.1.1-py3-none-any.whl.metadata (3.6 kB)
Using cached pip-25.1.1-py3-none-any.whl (1.8 MB)
  Attempting uninstall: pip
    Found existing installation: pip 24.3.1
    Uninstalling pip-24.3.1:
      Successfully uninstalled pip-24.3.1
Note: you may need to restart the kernel to use updated packages.


In [14]:
c = np.arange(24)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [15]:
c.ndim

1

In [ ]:
# This is comment

# This is h1
<h1>Hello I am single #</h1>

In [28]:
c = c.reshape(2,2,3,2) # [][][][]
c.ndim
c

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]]])

In [29]:
c.ndim

4

In [ ]:
# Suhel ->