In [1]:
print("This is second lecture")

This is second lecture


In [1]:
import numpy as np

In [4]:
b = np.array([[12, 34, 54],
             [23, 4,56],
             [2, 34,6],
             [2, 34,6],
             [2, 34,6],
             ])
print(b)

[[12 34 54]
 [23  4 56]
 [ 2 34  6]
 [ 2 34  6]
 [ 2 34  6]]


In [6]:
for i in range(5):
    for j in range(3):
        print(b[i][j])

12
34
54
23
4
56
2
34
6
2
34
6
2
34
6


In [2]:
ls = [1, 2, 3, 4, 5]

arr = np.array(ls)

arr

array([1, 2, 3, 4, 5])

In [3]:
print(type(ls))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [13]:
ls2 = [[1221, 34, 1254],
         [23, 4, 56],
         [ 2, 34,  6],
         [ 2, 34,  6],
         [ 2, 34,  6]]
l4 = ls2 + ls2
l4

[[1221, 34, 1254],
 [23, 4, 56],
 [2, 34, 6],
 [2, 34, 6],
 [2, 34, 6],
 [1221, 34, 1254],
 [23, 4, 56],
 [2, 34, 6],
 [2, 34, 6],
 [2, 34, 6]]

In [14]:
arr2 = np.array(ls2)
arr2

array([[1221,   34, 1254],
       [  23,    4,   56],
       [   2,   34,    6],
       [   2,   34,    6],
       [   2,   34,    6]])

In [15]:
m = arr2 + arr2
m

array([[2442,   68, 2508],
       [  46,    8,  112],
       [   4,   68,   12],
       [   4,   68,   12],
       [   4,   68,   12]])

In [16]:
m.itemsize

8

In [11]:
a = np.array([True, False])
a

array([ True, False])

In [12]:
a.itemsize

1