In [ ]:
import numpy as np

In [ ]:
arr = np.array([90, 34, 56, 67, 76])

In [ ]:
a1 = arr[0:3]

In [ ]:
a1

array([90, 34, 56])

In [ ]:
Arr = np.array([[3, 4, 5], [23, 46, 45], [23, 43, 55]])
Arr

array([[ 3,  4,  5],
       [23, 46, 45],
       [23, 43, 55]])

In [ ]:
a1 = Arr[0: 4, 1:3 ]

In [ ]:
a1

array([[ 4,  5],
       [46, 45],
       [43, 55]])